[ACA-4238] - added aspect list dialog on context menu action
Alfresco/alfresco-content-app pull request #2008
Opened 2021-02-19 16:14 UTC by VitoAlbano

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [X] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
No aspect list dialog is displayed

**What is the new behaviour?**
Aspect list dialog is displayed as context action

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-02-19 16:15 UTC, eromano approved these changes

2021-02-19 18:07 UTC, adinapitul commented
I see many different terminology used here: change aspect, edit aspect, aspect list, manage aspects.... Can we have some consistency?

2021-02-21 08:16 UTC, adinapitul requested changes
Same for all locked files expected actions

2021-02-21 08:16 UTC, adinapitul commented on e2e/suites/actions-available/files-folders/test-data.ts
> +  'Edit Aspects',
I'm pretty sure this is not ok. User should not be able to Edit Aspects if the file is locked

2021-02-22 06:20 UTC, adinapitul requested changes

2021-02-22 06:20 UTC, adinapitul commented on e2e/suites/actions-available/files-folders/test-data.ts
> +const multipleSelContextMenu = ['Download', 'Favorite', 'Move', 'Copy', 'Delete', 'Edit Aspects', 'Permissions'];
I'd say Edit Aspects should NOT be displayed for multiple selection

2021-02-24 05:08 UTC, adinapitul requested changes

2021-02-24 05:08 UTC, adinapitul commented on e2e/suites/actions-available/special-permissions/test-data-permissions.ts
> +const consumerContextMenu = ['Share', 'Download', 'View', 'Favorite', 'Copy', 'Edit Aspects', 'Manage Versions'];
Consumer and contributor should not see Edit Aspects.
Please revert this and check the docs.

2021-02-26 13:42 UTC, adinapitul approved these changes

2021-02-26 13:48 UTC, merged