ACA-1779: User with "Contributor" role on a site can't add a comment for a file/folder
Alfresco/alfresco-content-app pull request #2289
Opened 2021-09-09 09:09 UTC by amohammedalfresco

- Fixed missing `Add` comment option for user who may not own a file but has privileges to contribute it

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
In a repository service, a content not owned by a user but has been assigned with sufficient privileges to modify is not reflecting in ACA.  This behaviour is restricting adding a comment to a file that is not owned by a user of the site but been granted privileges (ex: `Contributor`).  The expected behaviour is available via RestApi and Share.

**What is the new behaviour?**
A proposed solution to remove extra layer of restriction as it is interfering with the original functionality of repository service.

**Does this PR introduce a breaking change?** (check one with "x")
Not sure :(
> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-09-09 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-content-app?pullRequest=2289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-content-app?pullRequest=2289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-content-app?pullRequest=2289) it.</sub>

2021-09-16 13:50 UTC, DenysVuika requested changes

2021-11-02 13:42 UTC, amohammedalfresco commented on src/app/components/info-drawer/comments-tab/comments-tab.component.ts
> -      return this.permission.check(this.node, ['update']);
Thanks for the review and sorry for a very late update on this.  I just refactored the code to guard scenarios where the current user is not the owner of the node, but has a role (Contributor, Collaborator or Manager) which allow it to comment.

2021-11-02 13:45 UTC, amohammedalfresco commented
I need to add unit tests to support changes/scenarios.

2021-11-05 14:13 UTC, eromano requested changes

2021-11-05 14:13 UTC, eromano commented on src/app/components/info-drawer/comments-tab/comments-tab.component.ts
> +  // comment: Comment;
maybe you forget this comment

2021-11-05 14:13 UTC, eromano commented on projects/aca-shared/src/lib/services/node-permission.service.ts
> +          if (nodeAuth.name === 'SiteContributor' || nodeAuth.name === 'SiteCollaborator' || nodeAuth.name === 'SiteManager') {
there is an enum in the JS-API for SiteContributor SiteCollaborator SiteManager better to use it

2021-11-05 14:13 UTC, eromano commented on src/app/components/info-drawer/comments-tab/comments-tab.component.ts
> +    from(this.groupService.listAllGroupMembershipsForPerson('-me-', { maxItems: 250 }))
what happen for more of 250?

2022-06-06 11:52 UTC, closed without merging