Redirection code added to check if app already exists in phone i.e an…
Alfresco/alfresco-content-app pull request #2856
Opened 2022-12-20 13:37 UTC by jatin2008

…droid or iphone otherwise opens in the browser

**Please check if the PR fulfills these requirements**

> - [ x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
Same behaviour as it was running earlier.

**What is the new behaviour?**
I have added code that will check whether device is Android or Iphone and if it encounters the android or iphone device then it will open the link in that application in the phone otherwise it will open the link in the browser.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2022-12-20 17:44 UTC, DenysVuika requested changes

2022-12-20 17:44 UTC, DenysVuika commented on app/src/app/content-plugin/components/shared-link-view/shared-link-view.component.ts
> +  sharedId: string = null;
why only shared link view has this functionality?

2022-12-20 17:44 UTC, DenysVuika commented on app/src/app/content-plugin/components/shared-link-view/shared-link-view.component.ts
> +      window.location.href = 'com.alfresco.contentapp://iosamw';
this should be coming from configuration

2022-12-20 17:44 UTC, DenysVuika commented on app/src/app/content-plugin/components/shared-link-view/shared-link-view.component.ts
> +      window.location.href = 'com.alfresco.content.app://androidamw://' + this.baseUrl + this.sharedId;
this should be coming from configuration

2022-12-20 18:36 UTC, DenysVuika commented
@jatin2008 please use the proper format of the PR title with the reference to the corresponding Jira. Also, this PR does not make much sense at you change the "shared link" viewer component only, and hardcode the stuff that should not be there

2022-12-21 11:44 UTC, closed without merging

2022-12-21 11:44 UTC, jatin2008 commented
revoking