[ACS-4586] Implemented Playwright Framework and add it to CI/CD
Alfresco/alfresco-content-app pull request #2985
Opened 2023-02-13 09:00 UTC by KikoUK

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [x] Other... Please describe:
Please see title

**What is the current behaviour?** (You can also link to an open issue here)
Please see title

**What is the new behaviour?**
Please see title

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-02-13 21:23 UTC, DenysVuika commented on e2e/playwright/shared/api/rules-api.ts
> +import { RuleTrigger } from '../../../../projects/aca-folder-rules/src/lib/model/rule.model';
incorrect paths in this file

2023-02-13 21:26 UTC, DenysVuika requested changes

2023-02-13 21:26 UTC, DenysVuika commented on e2e/playwright/shared/models/user-model.ts
> +  get fullName() {
missing return type 
```suggestion
  get fullName(): string {
```

2023-02-14 15:03 UTC, KikoUK commented on e2e/playwright/tests/folder-rules/fixtures/page-initialization.ts
> +export const test = base.extend<Pages & Api>({
`test` is a key word in playwright fixtures context. For more info, please see https://playwright.dev/docs/test-fixtures

2023-02-15 08:05 UTC, MichalKinas approved these changes

2023-02-16 17:22 UTC, DenysVuika approved these changes

2023-02-16 17:23 UTC, merged