[MNT-24034] Display updated properties after edit folder in dialog
Alfresco/alfresco-content-app pull request #3671
Opened 2024-02-27 08:41 UTC by tomson7777

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [x] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

The edit folder doesn't show previously updated values.

**What is the new behaviour?**

The edit folder shows previously updated values, for Name, Title, and Description respectively.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

2024-02-27 08:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/alfresco-content-app?pullRequest=3671) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/alfresco-content-app?pullRequest=3671) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/alfresco-content-app?pullRequest=3671) it.</sub>

2024-02-27 09:05 UTC, DominikIwanek approved these changes

2024-02-27 11:56 UTC, MichalKinas approved these changes
LGTM, please remember not to merge it until release is done :D

2024-02-27 13:48 UTC, DenysVuika approved these changes

2024-03-08 06:37 UTC, MichalKinas approved these changes

2024-04-10 11:18 UTC, datguychen requested changes

2024-04-10 11:18 UTC, datguychen commented on e2e/protractor/protractor.excludes.json
> +  "C280025": "will be fixed after protractor to playwright migration, see https://alfresco.atlassiana.net/browse/ACS-5007",
These tests should not be excluded, if they work properly.

2024-04-11 06:17 UTC, datguychen approved these changes

2024-04-11 07:38 UTC, merged