[ACS-8445] [ACA] Testing Angular 15 - Columns button is not centered properly
Alfresco/alfresco-content-app pull request #3970
Opened 2024-07-25 14:33 UTC by dominikiwanekhyland

**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://hyland.atlassian.net/browse/ACS-8445

**What is the new behaviour?**
Buttons are centered.

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-07-25 15:29 UTC, MichalKinas approved these changes

2024-07-26 06:39 UTC, nikita-web-ua commented on projects/aca-content/src/lib/ui/theme.scss
> +    margin-top: -10px;
this will break the layout for the icon buttons that previously were aligned properly, for example in toolbar

2024-07-26 13:24 UTC, DenysVuika requested changes

2024-07-26 13:24 UTC, DenysVuika commented on projects/aca-content/src/lib/ui/theme.scss
> +  #{$mat-icon} {
this is too risky change, you essentially change every icon in the button in the entire app

2024-07-31 08:42 UTC, MichalKinas approved these changes

2024-07-31 08:42 UTC, nikita-web-ua approved these changes

2024-07-31 12:15 UTC, DenysVuika commented on projects/aca-content/src/lib/ui/theme.scss
> +.adf-datatable-cell-header {
this needs to be in ADF so that all apps have the fix

2024-07-31 20:33 UTC, closed without merging