[ACS-8645][Legal Hold] ADW - context menu - hide unnecessary options
Alfresco/alfresco-content-app pull request #4064
Opened 2024-08-28 12:45 UTC by tamaragruszka

**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
https://hyland.atlassian.net/browse/ACS-8645

**What is the new behaviour?**
most options are hidden for files on hold

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2024-08-28 12:51 UTC, jacekpluta approved these changes

2024-08-28 15:08 UTC, dominikiwanekhyland approved these changes

2024-08-29 06:25 UTC, swapnil-verma-gl approved these changes

2024-08-29 15:12 UTC, DenysVuika commented on projects/aca-shared/rules/src/app.rules.ts
> +import { NodeEntry } from '@alfresco/js-api/typings';
should not have '/typings' in the import

2024-08-30 13:30 UTC, MichalKinas requested changes

2024-08-30 13:30 UTC, MichalKinas commented on projects/aca-shared/rules/src/app.rules.ts
> +export const isNodeFrozen = (_context: RuleContext, node: NodeEntry): boolean => !!node?.entry?.properties?.['rma:frozenAt'];
This aspect should only be available from governance, this rule should not be placed in ACA

2024-12-13 08:39 UTC, MichalKinas commented
Closing as this PR leeks enterprise code to community app, proper fix will be applied in enterprise repository.

2024-12-13 08:39 UTC, closed without merging